/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/Anlogic/EF2M45duino-master/ArduinoDemo/FPGAProject/al_ip/cortex_m3.v
 ** Date	:	2020 01 09
 ** TD version	:	4.6.14756
\************************************************************/

`timescale 1ns / 1ps

module cortex_m3 ( ppm_clk,
	gpio_h0_out,
	gpio_h0_oe_n,
	gpio_h0_in );

	input	ppm_clk;
	output	gpio_h0_out;
	output	gpio_h0_oe_n;
	input	gpio_h0_in;
	EF2_PHY_MCU #(
		.GPIO_L0("ENABLE"),
		.GPIO_L1("ENABLE"),
		.GPIO_L6("ENABLE"))
	mcu_inst(
		.ppm_clk(ppm_clk),
		.gpio_h_out({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,gpio_h0_out}),
		.gpio_h_oe_n({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,gpio_h0_oe_n}),
		.gpio_h_in({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,gpio_h0_in}));
endmodule